<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sms"
 *
 * Auto generated by Extension Builder 2021-01-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Short Message Service',
    'description' => 'Send SMS to FE Users via UI.',
    'category' => 'plugin',
    'author' => 'Nirmalya Mondal',
    'author_email' => 'nirmalya.mondal@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '10.4.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
